book_django_project/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
	url(r'^renting/', include('renting.urls')),
    url(r'^admin/', admin.site.urls),
]

renting/urls.py
from django.conf.urls import url

from . import views

app_name = 'renting'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^lenders', views.lenderview, name='lender'),
	url(r'^listings', views.listingview, name='listing')
]

renting/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.



class borrower(models.Model):
    borrower_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.CharField(max_length=50, blank=True)

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)

    class Meta:
		db_table = 'borrower'

class lender(models.Model):
    lender_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.CharField(max_length=50, blank=True)

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)

    class Meta:
		db_table = 'lender'

class listing(models.Model):
	listing_id = models.AutoField(primary_key=True)
	book_name = models.CharField(max_length=100)
	lender = models.ForeignKey('lender')
	days = models.IntegerField()
	price = models.IntegerField()
	returned = models.BooleanField()

	def __unicode__(self):
		return u'No.%d' % self.listing_id

	class Meta:
		db_table = 'listing'

class rental(models.Model):
    rental_id = models.AutoField(primary_key=True)
    listing_id = models.ForeignKey('listing')
    rental_date = models.DateTimeField(auto_now_add=True, blank=True)
    borrower = models.ForeignKey('borrower')
    lender = models.ForeignKey('lender')

    def __unicode__(self):
        return u'No.%d' % self.rental_id

    class Meta:
		db_table = 'rental'

renting/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import lender, borrower, rental, listing
# Create your views here.
from django.http import HttpResponse

def index(request):
	return render(request, 'renting/homepage.html')

def lenderview(request):
	lender_names = list(lender.objects.all())
	return render(request, 'renting/lender_list.html',{'names':lender_names})

def listingview(request):
	listing_names = list(listing.objects.all())
	return render(request, 'renting/listing_list.html', {'listings':listing_names})

templates/renting/homepage.html
<html>
    <p>Hi there!</p>
    <p>HTML for renting works!</p>
    <p>
    <a href='{% url 'renting:lender' %}'>Here</a> is a list of lenders.
    </p>
</html>

templates/renting/lender_list.html
<html>
<p> Here is a list of the lenders on this site</p>
<p>
{% for name in names %}
    {{ name }}
{% endfor %}
</p>
</html>

templates/renting/listing_list.html
<html>
<p> Here is a list of books available for renting</p>
<p>
<table style="width:80%">
{% for listing in listings %}
<tr>
	<th>
    {{ listing.book_name }}
    </th>
    <th>
    {{ listing.days }}
    </th>
    <th>
    {{ listing.price }}
    </th>
{% endfor %}
</tr>
</table>
</p>
</html>

templates/renting/renting_list.html
<html>
    <p>Hi there!</p>
    <p>Welcome to our book renting service!</p>
    <p>
    <a href='{% url 'renting:lender' %}'>Here</a> is a list of lenders.
    </p>
</html>